### ISSUE TITLE
Data should include which standard versions each version of an extension is compatible with

### ISSUE THREAD

**Issue by ghost** [open-contracting/extensions-data-collector#18]
For now, this is just copied from what the extension declares. But in the future more info may feed into this.

**Comment by jpmckinney** [comment]
Past releases may have:

* omitted compatibility, in which case they should set it to 1.1, as is already the case in the code
* specified 1.0, which is incorrect, and should be removed via the code

Why do we want a hardcoded list of known compatibility values?

**Comment by ghost** [comment]
> specified 1.0, which is incorrect, and should be removed via the code

Will do, thanks, will comment on #19.

> Why do we want a hardcoded list of known compatibility values?

I'm not sure I follow the question? If you mean STANDARD_COMPATIBILITY_VERSIONS in #19 because it's used elsewhere to build the data and to allow for easy future expansion. Maybe we can follow up on #19 if it's specifically related to that?

**Comment by jpmckinney** [comment]
Nevermind – In the end, avoiding a constant (`STANDARD_COMPATIBILITY_VERSIONS`) that needs to be updated for each major and minor version of OCDS (while still ensuring that extensions declare correct compatibilities) is more effort than having a constant.
